services:
  db:
    image: mysql:8.0
    container_name: cms-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [cms_net]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:6.6-apache
    container_name: cms-wordpress
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"   # WordPress → http://localhost:8080
    networks: [cms_net]

  phpmyadmin:
    image: phpmyadmin:5
    container_name: cms-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"   # phpMyAdmin → http://localhost:8081
    networks: [cms_net]

volumes:
  wordpress_data:
  mysql_data:

networks:
  cms_net:
    driver: bridge
