services:
  redis:
    image: redis:7-alpine
    container_name: app-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    networks: [app_net]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: app-backend
    environment:
      PORT: "8080"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      CACHE_TTL_SECONDS: "10"
    depends_on:
      redis:
        condition: service_healthy
    networks: [app_net]
    ports:
      - "8081:8080"   # бекенд доступний локально на http://localhost:8081

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:8080"  # фронтенд ходить у бек всередині мережі
    container_name: app-frontend
    depends_on:
      - backend
    networks: [app_net]
    ports:
      - "8080:80"     # фронтенд доступний локально на http://localhost:8080

volumes:
  redis_data:

networks:
  app_net:
    driver: bridge
